name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: source
          persist-credentials: false

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.access_token_public_key }}
          BRANCH: master
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm run build
